<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.example.org/model" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="Select">
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" lowerBound="1"
        upperBound="-1" eType="#//Column" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//From"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//Where"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="union" eType="#//Union"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnalias" eType="#//ColumnAlias"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="From">
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" upperBound="-1"
        eType="#//Table" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tablealias" eType="#//TableAlias"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Where">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanOperation" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonOperator" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Union">
    <eStructuralFeatures xsi:type="ecore:EReference" name="select" lowerBound="1"
        eType="#//Select" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equals" eSuperTypes="#//ComparisonOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="GreaterThan" eSuperTypes="#//ComparisonOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="LessThan" eSuperTypes="#//ComparisonOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="NotEquals" eSuperTypes="#//ComparisonOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//BooleanOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//BooleanOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnAlias">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableAlias">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="booleanoperation" eType="#//BooleanOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comparison" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lhs" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rhs" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comparisonoperator" lowerBound="1"
        eType="#//ComparisonOperator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Existence" abstract="true" interface="true"
      eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="select" lowerBound="1"
        eType="#//Select" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exists" eSuperTypes="#//Existence"/>
  <eClassifiers xsi:type="ecore:EClass" name="NotExists" eSuperTypes="#//Existence"/>
</ecore:EPackage>
