/*
 * generated by Xtext
 */
package org.xtext.ps3.school.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SchooldslUiModule extends org.xtext.ps3.school.ui.AbstractSchooldslUiModule {
	public SchooldslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
