/*
 * generated by Xtext
 */
package org.xtext.ps3.school;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SchooldslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.ps3.school.ui.internal.SchooldslActivator.getInstance().getInjector("org.xtext.ps3.school.Schooldsl");
	}
	
}
