/**
 * generated by Xtext
 */
package org.xtext.ps3.school.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
@SuppressWarnings("all")
public class SchooldslOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
