/*
 * generated by Xtext
 */
package org.xtext.ps3.school.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.ps3.school.ui.internal.SchooldslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SchooldslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SchooldslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SchooldslActivator.getInstance().getInjector(SchooldslActivator.ORG_XTEXT_PS3_SCHOOL_SCHOOLDSL);
	}
	
}
