/*
 * generated by Xtext
 */
package org.xtext.ps3.school.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.ps3.school.services.SchooldslGrammarAccess;

public class SchooldslParser extends AbstractContentAssistParser {
	
	@Inject
	private SchooldslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.ps3.school.ui.contentassist.antlr.internal.InternalSchooldslParser createParser() {
		org.xtext.ps3.school.ui.contentassist.antlr.internal.InternalSchooldslParser result = new org.xtext.ps3.school.ui.contentassist.antlr.internal.InternalSchooldslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getSchoolElementAccess().getAlternatives(), "rule__SchoolElement__Alternatives");
					put(grammarAccess.getSchoolDatabaseAccess().getGroup(), "rule__SchoolDatabase__Group__0");
					put(grammarAccess.getSchoolDatabaseAccess().getGroup_4(), "rule__SchoolDatabase__Group_4__0");
					put(grammarAccess.getSchoolDatabaseAccess().getGroup_4_3(), "rule__SchoolDatabase__Group_4_3__0");
					put(grammarAccess.getSchoolAccess().getGroup(), "rule__School__Group__0");
					put(grammarAccess.getSchoolAccess().getGroup_3(), "rule__School__Group_3__0");
					put(grammarAccess.getSchoolAccess().getGroup_3_3(), "rule__School__Group_3_3__0");
					put(grammarAccess.getSchoolAccess().getGroup_4(), "rule__School__Group_4__0");
					put(grammarAccess.getSchoolAccess().getGroup_4_3(), "rule__School__Group_4_3__0");
					put(grammarAccess.getSchoolAccess().getGroup_5(), "rule__School__Group_5__0");
					put(grammarAccess.getSchoolAccess().getGroup_5_3(), "rule__School__Group_5_3__0");
					put(grammarAccess.getSchoolAccess().getGroup_6(), "rule__School__Group_6__0");
					put(grammarAccess.getSchoolAccess().getGroup_6_3(), "rule__School__Group_6_3__0");
					put(grammarAccess.getSchoolAccess().getGroup_7(), "rule__School__Group_7__0");
					put(grammarAccess.getSchoolAccess().getGroup_7_3(), "rule__School__Group_7_3__0");
					put(grammarAccess.getQueryAccess().getGroup(), "rule__Query__Group__0");
					put(grammarAccess.getQueryAccess().getGroup_4(), "rule__Query__Group_4__0");
					put(grammarAccess.getFacultyAccess().getGroup(), "rule__Faculty__Group__0");
					put(grammarAccess.getFacultyAccess().getGroup_4(), "rule__Faculty__Group_4__0");
					put(grammarAccess.getFacultyAccess().getGroup_4_3(), "rule__Faculty__Group_4_3__0");
					put(grammarAccess.getCourseOfStudyAccess().getGroup(), "rule__CourseOfStudy__Group__0");
					put(grammarAccess.getCourseOfStudyAccess().getGroup_3(), "rule__CourseOfStudy__Group_3__0");
					put(grammarAccess.getCourseOfStudyAccess().getGroup_3_3(), "rule__CourseOfStudy__Group_3_3__0");
					put(grammarAccess.getCourseOfStudyAccess().getGroup_6(), "rule__CourseOfStudy__Group_6__0");
					put(grammarAccess.getCourseOfStudyAccess().getGroup_6_3(), "rule__CourseOfStudy__Group_6_3__0");
					put(grammarAccess.getCourseAccess().getGroup(), "rule__Course__Group__0");
					put(grammarAccess.getCourseAccess().getGroup_3(), "rule__Course__Group_3__0");
					put(grammarAccess.getCourseAccess().getGroup_4(), "rule__Course__Group_4__0");
					put(grammarAccess.getCourseAccess().getGroup_4_3(), "rule__Course__Group_4_3__0");
					put(grammarAccess.getCourseAccess().getGroup_7(), "rule__Course__Group_7__0");
					put(grammarAccess.getCourseAccess().getGroup_7_3(), "rule__Course__Group_7_3__0");
					put(grammarAccess.getStudentAccess().getGroup(), "rule__Student__Group__0");
					put(grammarAccess.getStudentAccess().getGroup_3(), "rule__Student__Group_3__0");
					put(grammarAccess.getStudentAccess().getGroup_4(), "rule__Student__Group_4__0");
					put(grammarAccess.getStudentAccess().getGroup_4_3(), "rule__Student__Group_4_3__0");
					put(grammarAccess.getTeacherAccess().getGroup(), "rule__Teacher__Group__0");
					put(grammarAccess.getTeacherAccess().getGroup_4(), "rule__Teacher__Group_4__0");
					put(grammarAccess.getTeacherAccess().getGroup_4_3(), "rule__Teacher__Group_4_3__0");
					put(grammarAccess.getCourseResultAccess().getGroup(), "rule__CourseResult__Group__0");
					put(grammarAccess.getCourseResultAccess().getGroup_2(), "rule__CourseResult__Group_2__0");
					put(grammarAccess.getEBigIntegerAccess().getGroup(), "rule__EBigInteger__Group__0");
					put(grammarAccess.getWhereAccess().getGroup(), "rule__Where__Group__0");
					put(grammarAccess.getBooleanExprAccess().getGroup(), "rule__BooleanExpr__Group__0");
					put(grammarAccess.getBooleanExprAccess().getGroup_4(), "rule__BooleanExpr__Group_4__0");
					put(grammarAccess.getBooleanExprAccess().getGroup_5(), "rule__BooleanExpr__Group_5__0");
					put(grammarAccess.getSchoolDatabaseAccess().getSchoolAssignment_3(), "rule__SchoolDatabase__SchoolAssignment_3");
					put(grammarAccess.getSchoolDatabaseAccess().getQueryAssignment_4_2(), "rule__SchoolDatabase__QueryAssignment_4_2");
					put(grammarAccess.getSchoolDatabaseAccess().getQueryAssignment_4_3_1(), "rule__SchoolDatabase__QueryAssignment_4_3_1");
					put(grammarAccess.getSchoolAccess().getNameAssignment_1(), "rule__School__NameAssignment_1");
					put(grammarAccess.getSchoolAccess().getFacultyAssignment_3_2(), "rule__School__FacultyAssignment_3_2");
					put(grammarAccess.getSchoolAccess().getFacultyAssignment_3_3_1(), "rule__School__FacultyAssignment_3_3_1");
					put(grammarAccess.getSchoolAccess().getCourseofstudyAssignment_4_2(), "rule__School__CourseofstudyAssignment_4_2");
					put(grammarAccess.getSchoolAccess().getCourseofstudyAssignment_4_3_1(), "rule__School__CourseofstudyAssignment_4_3_1");
					put(grammarAccess.getSchoolAccess().getCourseAssignment_5_2(), "rule__School__CourseAssignment_5_2");
					put(grammarAccess.getSchoolAccess().getCourseAssignment_5_3_1(), "rule__School__CourseAssignment_5_3_1");
					put(grammarAccess.getSchoolAccess().getStudentAssignment_6_2(), "rule__School__StudentAssignment_6_2");
					put(grammarAccess.getSchoolAccess().getStudentAssignment_6_3_1(), "rule__School__StudentAssignment_6_3_1");
					put(grammarAccess.getSchoolAccess().getTeacherAssignment_7_2(), "rule__School__TeacherAssignment_7_2");
					put(grammarAccess.getSchoolAccess().getTeacherAssignment_7_3_1(), "rule__School__TeacherAssignment_7_3_1");
					put(grammarAccess.getQueryAccess().getTypeAssignment_3(), "rule__Query__TypeAssignment_3");
					put(grammarAccess.getQueryAccess().getWhereAssignment_4_1(), "rule__Query__WhereAssignment_4_1");
					put(grammarAccess.getFacultyAccess().getNameAssignment_2(), "rule__Faculty__NameAssignment_2");
					put(grammarAccess.getFacultyAccess().getCourseofstudyAssignment_4_2(), "rule__Faculty__CourseofstudyAssignment_4_2");
					put(grammarAccess.getFacultyAccess().getCourseofstudyAssignment_4_3_1(), "rule__Faculty__CourseofstudyAssignment_4_3_1");
					put(grammarAccess.getCourseOfStudyAccess().getNameAssignment_1(), "rule__CourseOfStudy__NameAssignment_1");
					put(grammarAccess.getCourseOfStudyAccess().getCourseAssignment_3_2(), "rule__CourseOfStudy__CourseAssignment_3_2");
					put(grammarAccess.getCourseOfStudyAccess().getCourseAssignment_3_3_1(), "rule__CourseOfStudy__CourseAssignment_3_3_1");
					put(grammarAccess.getCourseOfStudyAccess().getFacultyAssignment_5(), "rule__CourseOfStudy__FacultyAssignment_5");
					put(grammarAccess.getCourseOfStudyAccess().getStudentAssignment_6_2(), "rule__CourseOfStudy__StudentAssignment_6_2");
					put(grammarAccess.getCourseOfStudyAccess().getStudentAssignment_6_3_1(), "rule__CourseOfStudy__StudentAssignment_6_3_1");
					put(grammarAccess.getCourseAccess().getNameAssignment_1(), "rule__Course__NameAssignment_1");
					put(grammarAccess.getCourseAccess().getCourseNumberAssignment_3_1(), "rule__Course__CourseNumberAssignment_3_1");
					put(grammarAccess.getCourseAccess().getEnrolledStudentAssignment_4_2(), "rule__Course__EnrolledStudentAssignment_4_2");
					put(grammarAccess.getCourseAccess().getEnrolledStudentAssignment_4_3_1(), "rule__Course__EnrolledStudentAssignment_4_3_1");
					put(grammarAccess.getCourseAccess().getTaughtByAssignment_6(), "rule__Course__TaughtByAssignment_6");
					put(grammarAccess.getCourseAccess().getCourseresultAssignment_7_2(), "rule__Course__CourseresultAssignment_7_2");
					put(grammarAccess.getCourseAccess().getCourseresultAssignment_7_3_1(), "rule__Course__CourseresultAssignment_7_3_1");
					put(grammarAccess.getStudentAccess().getNameAssignment_1(), "rule__Student__NameAssignment_1");
					put(grammarAccess.getStudentAccess().getStudentNumberAssignment_3_1(), "rule__Student__StudentNumberAssignment_3_1");
					put(grammarAccess.getStudentAccess().getEnrolledInAssignment_4_2(), "rule__Student__EnrolledInAssignment_4_2");
					put(grammarAccess.getStudentAccess().getEnrolledInAssignment_4_3_1(), "rule__Student__EnrolledInAssignment_4_3_1");
					put(grammarAccess.getStudentAccess().getCourseofstudyAssignment_6(), "rule__Student__CourseofstudyAssignment_6");
					put(grammarAccess.getTeacherAccess().getNameAssignment_2(), "rule__Teacher__NameAssignment_2");
					put(grammarAccess.getTeacherAccess().getTeachesAssignment_4_2(), "rule__Teacher__TeachesAssignment_4_2");
					put(grammarAccess.getTeacherAccess().getTeachesAssignment_4_3_1(), "rule__Teacher__TeachesAssignment_4_3_1");
					put(grammarAccess.getCourseResultAccess().getGradeAssignment_2_1(), "rule__CourseResult__GradeAssignment_2_1");
					put(grammarAccess.getCourseResultAccess().getStudentAssignment_4(), "rule__CourseResult__StudentAssignment_4");
					put(grammarAccess.getWhereAccess().getBooleanexprAssignment_1(), "rule__Where__BooleanexprAssignment_1");
					put(grammarAccess.getBooleanExprAccess().getLhsAssignment_1(), "rule__BooleanExpr__LhsAssignment_1");
					put(grammarAccess.getBooleanExprAccess().getOperatorAssignment_2(), "rule__BooleanExpr__OperatorAssignment_2");
					put(grammarAccess.getBooleanExprAccess().getRhsAssignment_3(), "rule__BooleanExpr__RhsAssignment_3");
					put(grammarAccess.getBooleanExprAccess().getAndAssignment_4_1(), "rule__BooleanExpr__AndAssignment_4_1");
					put(grammarAccess.getBooleanExprAccess().getOrAssignment_5_1(), "rule__BooleanExpr__OrAssignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.ps3.school.ui.contentassist.antlr.internal.InternalSchooldslParser typedParser = (org.xtext.ps3.school.ui.contentassist.antlr.internal.InternalSchooldslParser) parser;
			typedParser.entryRuleSchoolDatabase();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SchooldslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SchooldslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
