/**
 * generated by Xtext
 */
package org.xtext.ps3.school.ui.contentassist;

import org.xtext.ps3.school.ui.contentassist.AbstractSchooldslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SchooldslProposalProvider extends AbstractSchooldslProposalProvider {
}
