/**
 * generated by Xtext
 */
package org.xtext.ps3.school.validation;

import org.xtext.ps3.school.validation.AbstractSchooldslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SchooldslValidator extends AbstractSchooldslValidator {
}
