/**
 * generated by Xtext
 */
package org.xtext.ps3.school.serializer;

import org.xtext.ps3.school.serializer.AbstractSchooldslSemanticSequencer;

@SuppressWarnings("all")
public class SchooldslSemanticSequencer extends AbstractSchooldslSemanticSequencer {
}
