/**
 * generated by Xtext
 */
package org.xtext.ps3.school.serializer;

import org.xtext.ps3.school.serializer.AbstractSchooldslSyntacticSequencer;

@SuppressWarnings("all")
public class SchooldslSyntacticSequencer extends AbstractSchooldslSyntacticSequencer {
}
