/*
 * generated by Xtext
 */
package org.xtext.ps3.school.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class SchooldslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class SchoolDatabaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SchoolDatabase");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSchoolDatabaseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSchoolKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSchoolAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSchoolSchoolParserRuleCall_3_0 = (RuleCall)cSchoolAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cQueriesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cQueryAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cQueryQueryParserRuleCall_4_2_0 = (RuleCall)cQueryAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cQueryAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cQueryQueryParserRuleCall_4_3_1_0 = (RuleCall)cQueryAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//SchoolDatabase:
		//	"SchoolDatabase" "{" "school" school=School ("queries" "{" query+=Query ("," query+=Query)* "}")? "}";
		@Override public ParserRule getRule() { return rule; }

		//"SchoolDatabase" "{" "school" school=School ("queries" "{" query+=Query ("," query+=Query)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"SchoolDatabase"
		public Keyword getSchoolDatabaseKeyword_0() { return cSchoolDatabaseKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"school"
		public Keyword getSchoolKeyword_2() { return cSchoolKeyword_2; }

		//school=School
		public Assignment getSchoolAssignment_3() { return cSchoolAssignment_3; }

		//School
		public RuleCall getSchoolSchoolParserRuleCall_3_0() { return cSchoolSchoolParserRuleCall_3_0; }

		//("queries" "{" query+=Query ("," query+=Query)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"queries"
		public Keyword getQueriesKeyword_4_0() { return cQueriesKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//query+=Query
		public Assignment getQueryAssignment_4_2() { return cQueryAssignment_4_2; }

		//Query
		public RuleCall getQueryQueryParserRuleCall_4_2_0() { return cQueryQueryParserRuleCall_4_2_0; }

		//("," query+=Query)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//query+=Query
		public Assignment getQueryAssignment_4_3_1() { return cQueryAssignment_4_3_1; }

		//Query
		public RuleCall getQueryQueryParserRuleCall_4_3_1_0() { return cQueryQueryParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class SchoolElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "School");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSchoolAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFacultiesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cFacultyAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cFacultyFacultyParserRuleCall_3_2_0 = (RuleCall)cFacultyAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cFacultyAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cFacultyFacultyParserRuleCall_3_3_1_0 = (RuleCall)cFacultyAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCoursesofstudyKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cCourseofstudyAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cCourseofstudyCourseOfStudyParserRuleCall_4_2_0 = (RuleCall)cCourseofstudyAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cCourseofstudyAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cCourseofstudyCourseOfStudyParserRuleCall_4_3_1_0 = (RuleCall)cCourseofstudyAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCoursesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cCourseAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cCourseCourseParserRuleCall_5_2_0 = (RuleCall)cCourseAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cCourseAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cCourseCourseParserRuleCall_5_3_1_0 = (RuleCall)cCourseAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cStudentsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cStudentAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cStudentStudentParserRuleCall_6_2_0 = (RuleCall)cStudentAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cStudentAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cStudentStudentParserRuleCall_6_3_1_0 = (RuleCall)cStudentAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTeachersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cTeacherAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cTeacherTeacherParserRuleCall_7_2_0 = (RuleCall)cTeacherAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cTeacherAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cTeacherTeacherParserRuleCall_7_3_1_0 = (RuleCall)cTeacherAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//School:
		//	{School} name=EString "{" ("faculties" "{" faculty+=Faculty ("," faculty+=Faculty)* "}")? ("coursesofstudy" "{"
		//	courseofstudy+=CourseOfStudy ("," courseofstudy+=CourseOfStudy)* "}")? ("courses" "{" course+=Course (","
		//	course+=Course)* "}")? ("students" "{" student+=Student ("," student+=Student)* "}")? ("teachers" "{"
		//	teacher+=Teacher ("," teacher+=Teacher)* "}")? "}";
		@Override public ParserRule getRule() { return rule; }

		//{School} name=EString "{" ("faculties" "{" faculty+=Faculty ("," faculty+=Faculty)* "}")? ("coursesofstudy" "{"
		//courseofstudy+=CourseOfStudy ("," courseofstudy+=CourseOfStudy)* "}")? ("courses" "{" course+=Course (","
		//course+=Course)* "}")? ("students" "{" student+=Student ("," student+=Student)* "}")? ("teachers" "{" teacher+=Teacher
		//("," teacher+=Teacher)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{School}
		public Action getSchoolAction_0() { return cSchoolAction_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("faculties" "{" faculty+=Faculty ("," faculty+=Faculty)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"faculties"
		public Keyword getFacultiesKeyword_3_0() { return cFacultiesKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//faculty+=Faculty
		public Assignment getFacultyAssignment_3_2() { return cFacultyAssignment_3_2; }

		//Faculty
		public RuleCall getFacultyFacultyParserRuleCall_3_2_0() { return cFacultyFacultyParserRuleCall_3_2_0; }

		//("," faculty+=Faculty)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//faculty+=Faculty
		public Assignment getFacultyAssignment_3_3_1() { return cFacultyAssignment_3_3_1; }

		//Faculty
		public RuleCall getFacultyFacultyParserRuleCall_3_3_1_0() { return cFacultyFacultyParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//("coursesofstudy" "{" courseofstudy+=CourseOfStudy ("," courseofstudy+=CourseOfStudy)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"coursesofstudy"
		public Keyword getCoursesofstudyKeyword_4_0() { return cCoursesofstudyKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//courseofstudy+=CourseOfStudy
		public Assignment getCourseofstudyAssignment_4_2() { return cCourseofstudyAssignment_4_2; }

		//CourseOfStudy
		public RuleCall getCourseofstudyCourseOfStudyParserRuleCall_4_2_0() { return cCourseofstudyCourseOfStudyParserRuleCall_4_2_0; }

		//("," courseofstudy+=CourseOfStudy)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//courseofstudy+=CourseOfStudy
		public Assignment getCourseofstudyAssignment_4_3_1() { return cCourseofstudyAssignment_4_3_1; }

		//CourseOfStudy
		public RuleCall getCourseofstudyCourseOfStudyParserRuleCall_4_3_1_0() { return cCourseofstudyCourseOfStudyParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//("courses" "{" course+=Course ("," course+=Course)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"courses"
		public Keyword getCoursesKeyword_5_0() { return cCoursesKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//course+=Course
		public Assignment getCourseAssignment_5_2() { return cCourseAssignment_5_2; }

		//Course
		public RuleCall getCourseCourseParserRuleCall_5_2_0() { return cCourseCourseParserRuleCall_5_2_0; }

		//("," course+=Course)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//course+=Course
		public Assignment getCourseAssignment_5_3_1() { return cCourseAssignment_5_3_1; }

		//Course
		public RuleCall getCourseCourseParserRuleCall_5_3_1_0() { return cCourseCourseParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("students" "{" student+=Student ("," student+=Student)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"students"
		public Keyword getStudentsKeyword_6_0() { return cStudentsKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//student+=Student
		public Assignment getStudentAssignment_6_2() { return cStudentAssignment_6_2; }

		//Student
		public RuleCall getStudentStudentParserRuleCall_6_2_0() { return cStudentStudentParserRuleCall_6_2_0; }

		//("," student+=Student)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//student+=Student
		public Assignment getStudentAssignment_6_3_1() { return cStudentAssignment_6_3_1; }

		//Student
		public RuleCall getStudentStudentParserRuleCall_6_3_1_0() { return cStudentStudentParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//("teachers" "{" teacher+=Teacher ("," teacher+=Teacher)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"teachers"
		public Keyword getTeachersKeyword_7_0() { return cTeachersKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//teacher+=Teacher
		public Assignment getTeacherAssignment_7_2() { return cTeacherAssignment_7_2; }

		//Teacher
		public RuleCall getTeacherTeacherParserRuleCall_7_2_0() { return cTeacherTeacherParserRuleCall_7_2_0; }

		//("," teacher+=Teacher)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//teacher+=Teacher
		public Assignment getTeacherAssignment_7_3_1() { return cTeacherAssignment_7_3_1; }

		//Teacher
		public RuleCall getTeacherTeacherParserRuleCall_7_3_1_0() { return cTeacherTeacherParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class QueryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Query");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cQueryAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cQueryKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeSchoolElementEnumRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWhereKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cWhereAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cWhereWhereParserRuleCall_4_1_0 = (RuleCall)cWhereAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Query:
		//	{Query} "Query" "{" type=SchoolElement? ("where" where=Where)? "}";
		@Override public ParserRule getRule() { return rule; }

		//{Query} "Query" "{" type=SchoolElement? ("where" where=Where)? "}"
		public Group getGroup() { return cGroup; }

		//{Query}
		public Action getQueryAction_0() { return cQueryAction_0; }

		//"Query"
		public Keyword getQueryKeyword_1() { return cQueryKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//type=SchoolElement?
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }

		//SchoolElement
		public RuleCall getTypeSchoolElementEnumRuleCall_3_0() { return cTypeSchoolElementEnumRuleCall_3_0; }

		//("where" where=Where)?
		public Group getGroup_4() { return cGroup_4; }

		//"where"
		public Keyword getWhereKeyword_4_0() { return cWhereKeyword_4_0; }

		//where=Where
		public Assignment getWhereAssignment_4_1() { return cWhereAssignment_4_1; }

		//Where
		public RuleCall getWhereWhereParserRuleCall_4_1_0() { return cWhereWhereParserRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class FacultyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Faculty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFacultyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFacultyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCoursesofstudyKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cCourseofstudyAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cCourseofstudyCourseOfStudyCrossReference_4_2_0 = (CrossReference)cCourseofstudyAssignment_4_2.eContents().get(0);
		private final RuleCall cCourseofstudyCourseOfStudyEStringParserRuleCall_4_2_0_1 = (RuleCall)cCourseofstudyCourseOfStudyCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cCourseofstudyAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cCourseofstudyCourseOfStudyCrossReference_4_3_1_0 = (CrossReference)cCourseofstudyAssignment_4_3_1.eContents().get(0);
		private final RuleCall cCourseofstudyCourseOfStudyEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cCourseofstudyCourseOfStudyCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Faculty:
		//	{Faculty} "Faculty" name=EString "{" ("coursesofstudy" "(" courseofstudy+=[CourseOfStudy|EString] (","
		//	courseofstudy+=[CourseOfStudy|EString])* ")")? "}";
		@Override public ParserRule getRule() { return rule; }

		//{Faculty} "Faculty" name=EString "{" ("coursesofstudy" "(" courseofstudy+=[CourseOfStudy|EString] (","
		//courseofstudy+=[CourseOfStudy|EString])* ")")? "}"
		public Group getGroup() { return cGroup; }

		//{Faculty}
		public Action getFacultyAction_0() { return cFacultyAction_0; }

		//"Faculty"
		public Keyword getFacultyKeyword_1() { return cFacultyKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("coursesofstudy" "(" courseofstudy+=[CourseOfStudy|EString] ("," courseofstudy+=[CourseOfStudy|EString])* ")")?
		public Group getGroup_4() { return cGroup_4; }

		//"coursesofstudy"
		public Keyword getCoursesofstudyKeyword_4_0() { return cCoursesofstudyKeyword_4_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }

		//courseofstudy+=[CourseOfStudy|EString]
		public Assignment getCourseofstudyAssignment_4_2() { return cCourseofstudyAssignment_4_2; }

		//[CourseOfStudy|EString]
		public CrossReference getCourseofstudyCourseOfStudyCrossReference_4_2_0() { return cCourseofstudyCourseOfStudyCrossReference_4_2_0; }

		//EString
		public RuleCall getCourseofstudyCourseOfStudyEStringParserRuleCall_4_2_0_1() { return cCourseofstudyCourseOfStudyEStringParserRuleCall_4_2_0_1; }

		//("," courseofstudy+=[CourseOfStudy|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//courseofstudy+=[CourseOfStudy|EString]
		public Assignment getCourseofstudyAssignment_4_3_1() { return cCourseofstudyAssignment_4_3_1; }

		//[CourseOfStudy|EString]
		public CrossReference getCourseofstudyCourseOfStudyCrossReference_4_3_1_0() { return cCourseofstudyCourseOfStudyCrossReference_4_3_1_0; }

		//EString
		public RuleCall getCourseofstudyCourseOfStudyEStringParserRuleCall_4_3_1_0_1() { return cCourseofstudyCourseOfStudyEStringParserRuleCall_4_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class CourseOfStudyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CourseOfStudy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCourseOfStudyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCoursesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cCourseAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cCourseCourseCrossReference_3_2_0 = (CrossReference)cCourseAssignment_3_2.eContents().get(0);
		private final RuleCall cCourseCourseEStringParserRuleCall_3_2_0_1 = (RuleCall)cCourseCourseCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cCourseAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cCourseCourseCrossReference_3_3_1_0 = (CrossReference)cCourseAssignment_3_3_1.eContents().get(0);
		private final RuleCall cCourseCourseEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cCourseCourseCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cFacultyKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFacultyAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cFacultyFacultyCrossReference_5_0 = (CrossReference)cFacultyAssignment_5.eContents().get(0);
		private final RuleCall cFacultyFacultyEStringParserRuleCall_5_0_1 = (RuleCall)cFacultyFacultyCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cStudentsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cStudentAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cStudentStudentCrossReference_6_2_0 = (CrossReference)cStudentAssignment_6_2.eContents().get(0);
		private final RuleCall cStudentStudentEStringParserRuleCall_6_2_0_1 = (RuleCall)cStudentStudentCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cStudentAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cStudentStudentCrossReference_6_3_1_0 = (CrossReference)cStudentAssignment_6_3_1.eContents().get(0);
		private final RuleCall cStudentStudentEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cStudentStudentCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//CourseOfStudy:
		//	"CourseOfStudy" name=EString "{" ("courses" "(" course+=[Course|EString] ("," course+=[Course|EString])* ")")?
		//	"faculty" faculty=[Faculty|EString] ("students" "(" student+=[Student|EString] ("," student+=[Student|EString])*
		//	")")? "}";
		@Override public ParserRule getRule() { return rule; }

		//"CourseOfStudy" name=EString "{" ("courses" "(" course+=[Course|EString] ("," course+=[Course|EString])* ")")? "faculty"
		//faculty=[Faculty|EString] ("students" "(" student+=[Student|EString] ("," student+=[Student|EString])* ")")? "}"
		public Group getGroup() { return cGroup; }

		//"CourseOfStudy"
		public Keyword getCourseOfStudyKeyword_0() { return cCourseOfStudyKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("courses" "(" course+=[Course|EString] ("," course+=[Course|EString])* ")")?
		public Group getGroup_3() { return cGroup_3; }

		//"courses"
		public Keyword getCoursesKeyword_3_0() { return cCoursesKeyword_3_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }

		//course+=[Course|EString]
		public Assignment getCourseAssignment_3_2() { return cCourseAssignment_3_2; }

		//[Course|EString]
		public CrossReference getCourseCourseCrossReference_3_2_0() { return cCourseCourseCrossReference_3_2_0; }

		//EString
		public RuleCall getCourseCourseEStringParserRuleCall_3_2_0_1() { return cCourseCourseEStringParserRuleCall_3_2_0_1; }

		//("," course+=[Course|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//course+=[Course|EString]
		public Assignment getCourseAssignment_3_3_1() { return cCourseAssignment_3_3_1; }

		//[Course|EString]
		public CrossReference getCourseCourseCrossReference_3_3_1_0() { return cCourseCourseCrossReference_3_3_1_0; }

		//EString
		public RuleCall getCourseCourseEStringParserRuleCall_3_3_1_0_1() { return cCourseCourseEStringParserRuleCall_3_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }

		//"faculty"
		public Keyword getFacultyKeyword_4() { return cFacultyKeyword_4; }

		//faculty=[Faculty|EString]
		public Assignment getFacultyAssignment_5() { return cFacultyAssignment_5; }

		//[Faculty|EString]
		public CrossReference getFacultyFacultyCrossReference_5_0() { return cFacultyFacultyCrossReference_5_0; }

		//EString
		public RuleCall getFacultyFacultyEStringParserRuleCall_5_0_1() { return cFacultyFacultyEStringParserRuleCall_5_0_1; }

		//("students" "(" student+=[Student|EString] ("," student+=[Student|EString])* ")")?
		public Group getGroup_6() { return cGroup_6; }

		//"students"
		public Keyword getStudentsKeyword_6_0() { return cStudentsKeyword_6_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }

		//student+=[Student|EString]
		public Assignment getStudentAssignment_6_2() { return cStudentAssignment_6_2; }

		//[Student|EString]
		public CrossReference getStudentStudentCrossReference_6_2_0() { return cStudentStudentCrossReference_6_2_0; }

		//EString
		public RuleCall getStudentStudentEStringParserRuleCall_6_2_0_1() { return cStudentStudentEStringParserRuleCall_6_2_0_1; }

		//("," student+=[Student|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//student+=[Student|EString]
		public Assignment getStudentAssignment_6_3_1() { return cStudentAssignment_6_3_1; }

		//[Student|EString]
		public CrossReference getStudentStudentCrossReference_6_3_1_0() { return cStudentStudentCrossReference_6_3_1_0; }

		//EString
		public RuleCall getStudentStudentEStringParserRuleCall_6_3_1_0_1() { return cStudentStudentEStringParserRuleCall_6_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class CourseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Course");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCourseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCourseNumberKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCourseNumberAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCourseNumberEStringParserRuleCall_3_1_0 = (RuleCall)cCourseNumberAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEnrolledStudentsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cEnrolledStudentAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cEnrolledStudentStudentCrossReference_4_2_0 = (CrossReference)cEnrolledStudentAssignment_4_2.eContents().get(0);
		private final RuleCall cEnrolledStudentStudentEStringParserRuleCall_4_2_0_1 = (RuleCall)cEnrolledStudentStudentCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cEnrolledStudentAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cEnrolledStudentStudentCrossReference_4_3_1_0 = (CrossReference)cEnrolledStudentAssignment_4_3_1.eContents().get(0);
		private final RuleCall cEnrolledStudentStudentEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cEnrolledStudentStudentCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cTaughtByKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTaughtByAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cTaughtByTeacherCrossReference_6_0 = (CrossReference)cTaughtByAssignment_6.eContents().get(0);
		private final RuleCall cTaughtByTeacherEStringParserRuleCall_6_0_1 = (RuleCall)cTaughtByTeacherCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCourseresultsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cCourseresultAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cCourseresultCourseResultParserRuleCall_7_2_0 = (RuleCall)cCourseresultAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cCourseresultAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cCourseresultCourseResultParserRuleCall_7_3_1_0 = (RuleCall)cCourseresultAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Course:
		//	"Course" name=EString "{" ("courseNumber" courseNumber=EString)? ("enrolledStudents" "("
		//	enrolledStudent+=[Student|EString] ("," enrolledStudent+=[Student|EString])* ")")? "taughtBy"
		//	taughtBy=[Teacher|EString] ("courseresults" "{" courseresult+=CourseResult ("," courseresult+=CourseResult)* "}")?
		//	"}";
		@Override public ParserRule getRule() { return rule; }

		//"Course" name=EString "{" ("courseNumber" courseNumber=EString)? ("enrolledStudents" "("
		//enrolledStudent+=[Student|EString] ("," enrolledStudent+=[Student|EString])* ")")? "taughtBy"
		//taughtBy=[Teacher|EString] ("courseresults" "{" courseresult+=CourseResult ("," courseresult+=CourseResult)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"Course"
		public Keyword getCourseKeyword_0() { return cCourseKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("courseNumber" courseNumber=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"courseNumber"
		public Keyword getCourseNumberKeyword_3_0() { return cCourseNumberKeyword_3_0; }

		//courseNumber=EString
		public Assignment getCourseNumberAssignment_3_1() { return cCourseNumberAssignment_3_1; }

		//EString
		public RuleCall getCourseNumberEStringParserRuleCall_3_1_0() { return cCourseNumberEStringParserRuleCall_3_1_0; }

		//("enrolledStudents" "(" enrolledStudent+=[Student|EString] ("," enrolledStudent+=[Student|EString])* ")")?
		public Group getGroup_4() { return cGroup_4; }

		//"enrolledStudents"
		public Keyword getEnrolledStudentsKeyword_4_0() { return cEnrolledStudentsKeyword_4_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }

		//enrolledStudent+=[Student|EString]
		public Assignment getEnrolledStudentAssignment_4_2() { return cEnrolledStudentAssignment_4_2; }

		//[Student|EString]
		public CrossReference getEnrolledStudentStudentCrossReference_4_2_0() { return cEnrolledStudentStudentCrossReference_4_2_0; }

		//EString
		public RuleCall getEnrolledStudentStudentEStringParserRuleCall_4_2_0_1() { return cEnrolledStudentStudentEStringParserRuleCall_4_2_0_1; }

		//("," enrolledStudent+=[Student|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//enrolledStudent+=[Student|EString]
		public Assignment getEnrolledStudentAssignment_4_3_1() { return cEnrolledStudentAssignment_4_3_1; }

		//[Student|EString]
		public CrossReference getEnrolledStudentStudentCrossReference_4_3_1_0() { return cEnrolledStudentStudentCrossReference_4_3_1_0; }

		//EString
		public RuleCall getEnrolledStudentStudentEStringParserRuleCall_4_3_1_0_1() { return cEnrolledStudentStudentEStringParserRuleCall_4_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }

		//"taughtBy"
		public Keyword getTaughtByKeyword_5() { return cTaughtByKeyword_5; }

		//taughtBy=[Teacher|EString]
		public Assignment getTaughtByAssignment_6() { return cTaughtByAssignment_6; }

		//[Teacher|EString]
		public CrossReference getTaughtByTeacherCrossReference_6_0() { return cTaughtByTeacherCrossReference_6_0; }

		//EString
		public RuleCall getTaughtByTeacherEStringParserRuleCall_6_0_1() { return cTaughtByTeacherEStringParserRuleCall_6_0_1; }

		//("courseresults" "{" courseresult+=CourseResult ("," courseresult+=CourseResult)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"courseresults"
		public Keyword getCourseresultsKeyword_7_0() { return cCourseresultsKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//courseresult+=CourseResult
		public Assignment getCourseresultAssignment_7_2() { return cCourseresultAssignment_7_2; }

		//CourseResult
		public RuleCall getCourseresultCourseResultParserRuleCall_7_2_0() { return cCourseresultCourseResultParserRuleCall_7_2_0; }

		//("," courseresult+=CourseResult)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//courseresult+=CourseResult
		public Assignment getCourseresultAssignment_7_3_1() { return cCourseresultAssignment_7_3_1; }

		//CourseResult
		public RuleCall getCourseresultCourseResultParserRuleCall_7_3_1_0() { return cCourseresultCourseResultParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class StudentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Student");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStudentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cStudentNumberKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cStudentNumberAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cStudentNumberEStringParserRuleCall_3_1_0 = (RuleCall)cStudentNumberAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEnrolledInKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cEnrolledInAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cEnrolledInCourseCrossReference_4_2_0 = (CrossReference)cEnrolledInAssignment_4_2.eContents().get(0);
		private final RuleCall cEnrolledInCourseEStringParserRuleCall_4_2_0_1 = (RuleCall)cEnrolledInCourseCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cEnrolledInAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cEnrolledInCourseCrossReference_4_3_1_0 = (CrossReference)cEnrolledInAssignment_4_3_1.eContents().get(0);
		private final RuleCall cEnrolledInCourseEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cEnrolledInCourseCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cCourseofstudyKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCourseofstudyAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cCourseofstudyCourseOfStudyCrossReference_6_0 = (CrossReference)cCourseofstudyAssignment_6.eContents().get(0);
		private final RuleCall cCourseofstudyCourseOfStudyEStringParserRuleCall_6_0_1 = (RuleCall)cCourseofstudyCourseOfStudyCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Student:
		//	"Student" name=EString "{" ("studentNumber" studentNumber=EString)? ("enrolledIn" "(" enrolledIn+=[Course|EString]
		//	("," enrolledIn+=[Course|EString])* ")")? "courseofstudy" courseofstudy=[CourseOfStudy|EString] "}";
		@Override public ParserRule getRule() { return rule; }

		//"Student" name=EString "{" ("studentNumber" studentNumber=EString)? ("enrolledIn" "(" enrolledIn+=[Course|EString] (","
		//enrolledIn+=[Course|EString])* ")")? "courseofstudy" courseofstudy=[CourseOfStudy|EString] "}"
		public Group getGroup() { return cGroup; }

		//"Student"
		public Keyword getStudentKeyword_0() { return cStudentKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("studentNumber" studentNumber=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"studentNumber"
		public Keyword getStudentNumberKeyword_3_0() { return cStudentNumberKeyword_3_0; }

		//studentNumber=EString
		public Assignment getStudentNumberAssignment_3_1() { return cStudentNumberAssignment_3_1; }

		//EString
		public RuleCall getStudentNumberEStringParserRuleCall_3_1_0() { return cStudentNumberEStringParserRuleCall_3_1_0; }

		//("enrolledIn" "(" enrolledIn+=[Course|EString] ("," enrolledIn+=[Course|EString])* ")")?
		public Group getGroup_4() { return cGroup_4; }

		//"enrolledIn"
		public Keyword getEnrolledInKeyword_4_0() { return cEnrolledInKeyword_4_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }

		//enrolledIn+=[Course|EString]
		public Assignment getEnrolledInAssignment_4_2() { return cEnrolledInAssignment_4_2; }

		//[Course|EString]
		public CrossReference getEnrolledInCourseCrossReference_4_2_0() { return cEnrolledInCourseCrossReference_4_2_0; }

		//EString
		public RuleCall getEnrolledInCourseEStringParserRuleCall_4_2_0_1() { return cEnrolledInCourseEStringParserRuleCall_4_2_0_1; }

		//("," enrolledIn+=[Course|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//enrolledIn+=[Course|EString]
		public Assignment getEnrolledInAssignment_4_3_1() { return cEnrolledInAssignment_4_3_1; }

		//[Course|EString]
		public CrossReference getEnrolledInCourseCrossReference_4_3_1_0() { return cEnrolledInCourseCrossReference_4_3_1_0; }

		//EString
		public RuleCall getEnrolledInCourseEStringParserRuleCall_4_3_1_0_1() { return cEnrolledInCourseEStringParserRuleCall_4_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }

		//"courseofstudy"
		public Keyword getCourseofstudyKeyword_5() { return cCourseofstudyKeyword_5; }

		//courseofstudy=[CourseOfStudy|EString]
		public Assignment getCourseofstudyAssignment_6() { return cCourseofstudyAssignment_6; }

		//[CourseOfStudy|EString]
		public CrossReference getCourseofstudyCourseOfStudyCrossReference_6_0() { return cCourseofstudyCourseOfStudyCrossReference_6_0; }

		//EString
		public RuleCall getCourseofstudyCourseOfStudyEStringParserRuleCall_6_0_1() { return cCourseofstudyCourseOfStudyEStringParserRuleCall_6_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class TeacherElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Teacher");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTeacherAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTeacherKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTeachesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cTeachesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cTeachesCourseCrossReference_4_2_0 = (CrossReference)cTeachesAssignment_4_2.eContents().get(0);
		private final RuleCall cTeachesCourseEStringParserRuleCall_4_2_0_1 = (RuleCall)cTeachesCourseCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cTeachesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cTeachesCourseCrossReference_4_3_1_0 = (CrossReference)cTeachesAssignment_4_3_1.eContents().get(0);
		private final RuleCall cTeachesCourseEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cTeachesCourseCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Teacher:
		//	{Teacher} "Teacher" name=EString "{" ("teaches" "(" teaches+=[Course|EString] ("," teaches+=[Course|EString])* ")")?
		//	"}";
		@Override public ParserRule getRule() { return rule; }

		//{Teacher} "Teacher" name=EString "{" ("teaches" "(" teaches+=[Course|EString] ("," teaches+=[Course|EString])* ")")? "}"
		public Group getGroup() { return cGroup; }

		//{Teacher}
		public Action getTeacherAction_0() { return cTeacherAction_0; }

		//"Teacher"
		public Keyword getTeacherKeyword_1() { return cTeacherKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("teaches" "(" teaches+=[Course|EString] ("," teaches+=[Course|EString])* ")")?
		public Group getGroup_4() { return cGroup_4; }

		//"teaches"
		public Keyword getTeachesKeyword_4_0() { return cTeachesKeyword_4_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }

		//teaches+=[Course|EString]
		public Assignment getTeachesAssignment_4_2() { return cTeachesAssignment_4_2; }

		//[Course|EString]
		public CrossReference getTeachesCourseCrossReference_4_2_0() { return cTeachesCourseCrossReference_4_2_0; }

		//EString
		public RuleCall getTeachesCourseEStringParserRuleCall_4_2_0_1() { return cTeachesCourseEStringParserRuleCall_4_2_0_1; }

		//("," teaches+=[Course|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//teaches+=[Course|EString]
		public Assignment getTeachesAssignment_4_3_1() { return cTeachesAssignment_4_3_1; }

		//[Course|EString]
		public CrossReference getTeachesCourseCrossReference_4_3_1_0() { return cTeachesCourseCrossReference_4_3_1_0; }

		//EString
		public RuleCall getTeachesCourseEStringParserRuleCall_4_3_1_0_1() { return cTeachesCourseEStringParserRuleCall_4_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class CourseResultElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CourseResult");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCourseResultKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cGradeKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cGradeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cGradeEBigIntegerParserRuleCall_2_1_0 = (RuleCall)cGradeAssignment_2_1.eContents().get(0);
		private final Keyword cStudentKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStudentAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cStudentStudentCrossReference_4_0 = (CrossReference)cStudentAssignment_4.eContents().get(0);
		private final RuleCall cStudentStudentEStringParserRuleCall_4_0_1 = (RuleCall)cStudentStudentCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//CourseResult:
		//	"CourseResult" "{" ("grade" grade=EBigInteger)? "student" student=[Student|EString] "}";
		@Override public ParserRule getRule() { return rule; }

		//"CourseResult" "{" ("grade" grade=EBigInteger)? "student" student=[Student|EString] "}"
		public Group getGroup() { return cGroup; }

		//"CourseResult"
		public Keyword getCourseResultKeyword_0() { return cCourseResultKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("grade" grade=EBigInteger)?
		public Group getGroup_2() { return cGroup_2; }

		//"grade"
		public Keyword getGradeKeyword_2_0() { return cGradeKeyword_2_0; }

		//grade=EBigInteger
		public Assignment getGradeAssignment_2_1() { return cGradeAssignment_2_1; }

		//EBigInteger
		public RuleCall getGradeEBigIntegerParserRuleCall_2_1_0() { return cGradeEBigIntegerParserRuleCall_2_1_0; }

		//"student"
		public Keyword getStudentKeyword_3() { return cStudentKeyword_3; }

		//student=[Student|EString]
		public Assignment getStudentAssignment_4() { return cStudentAssignment_4; }

		//[Student|EString]
		public CrossReference getStudentStudentCrossReference_4_0() { return cStudentStudentCrossReference_4_0; }

		//EString
		public RuleCall getStudentStudentEStringParserRuleCall_4_0_1() { return cStudentStudentEStringParserRuleCall_4_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EBigIntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBigInteger");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EBigInteger returns ecore::EBigInteger:
		//	"-"? INT;
		@Override public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class WhereElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Where");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cBooleanexprAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cBooleanexprBooleanExprParserRuleCall_1_0 = (RuleCall)cBooleanexprAssignment_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Where:
		//	"{" booleanexpr=BooleanExpr "}";
		@Override public ParserRule getRule() { return rule; }

		//"{" booleanexpr=BooleanExpr "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//booleanexpr=BooleanExpr
		public Assignment getBooleanexprAssignment_1() { return cBooleanexprAssignment_1; }

		//BooleanExpr
		public RuleCall getBooleanexprBooleanExprParserRuleCall_1_0() { return cBooleanexprBooleanExprParserRuleCall_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}

	public class BooleanExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BooleanExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBooleanExprAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cLhsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLhsEStringParserRuleCall_1_0 = (RuleCall)cLhsAssignment_1.eContents().get(0);
		private final Assignment cOperatorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOperatorEStringParserRuleCall_2_0 = (RuleCall)cOperatorAssignment_2.eContents().get(0);
		private final Assignment cRhsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRhsEStringParserRuleCall_3_0 = (RuleCall)cRhsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAndKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAndAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAndBooleanExprParserRuleCall_4_1_0 = (RuleCall)cAndAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOrKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cOrAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cOrBooleanExprParserRuleCall_5_1_0 = (RuleCall)cOrAssignment_5_1.eContents().get(0);
		
		//BooleanExpr:
		//	{BooleanExpr} lhs=EString operator=EString rhs=EString ("and" and=BooleanExpr)? ("or" or=BooleanExpr)?;
		@Override public ParserRule getRule() { return rule; }

		//{BooleanExpr} lhs=EString operator=EString rhs=EString ("and" and=BooleanExpr)? ("or" or=BooleanExpr)?
		public Group getGroup() { return cGroup; }

		//{BooleanExpr}
		public Action getBooleanExprAction_0() { return cBooleanExprAction_0; }

		//lhs=EString
		public Assignment getLhsAssignment_1() { return cLhsAssignment_1; }

		//EString
		public RuleCall getLhsEStringParserRuleCall_1_0() { return cLhsEStringParserRuleCall_1_0; }

		//operator=EString
		public Assignment getOperatorAssignment_2() { return cOperatorAssignment_2; }

		//EString
		public RuleCall getOperatorEStringParserRuleCall_2_0() { return cOperatorEStringParserRuleCall_2_0; }

		//rhs=EString
		public Assignment getRhsAssignment_3() { return cRhsAssignment_3; }

		//EString
		public RuleCall getRhsEStringParserRuleCall_3_0() { return cRhsEStringParserRuleCall_3_0; }

		//("and" and=BooleanExpr)?
		public Group getGroup_4() { return cGroup_4; }

		//"and"
		public Keyword getAndKeyword_4_0() { return cAndKeyword_4_0; }

		//and=BooleanExpr
		public Assignment getAndAssignment_4_1() { return cAndAssignment_4_1; }

		//BooleanExpr
		public RuleCall getAndBooleanExprParserRuleCall_4_1_0() { return cAndBooleanExprParserRuleCall_4_1_0; }

		//("or" or=BooleanExpr)?
		public Group getGroup_5() { return cGroup_5; }

		//"or"
		public Keyword getOrKeyword_5_0() { return cOrKeyword_5_0; }

		//or=BooleanExpr
		public Assignment getOrAssignment_5_1() { return cOrAssignment_5_1; }

		//BooleanExpr
		public RuleCall getOrBooleanExprParserRuleCall_5_1_0() { return cOrBooleanExprParserRuleCall_5_1_0; }
	}
	
	
	public class SchoolElementElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "SchoolElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSchoolEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSchoolSchoolKeyword_0_0 = (Keyword)cSchoolEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cStudentEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cStudentStudentKeyword_1_0 = (Keyword)cStudentEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cTeacherEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cTeacherTeacherKeyword_2_0 = (Keyword)cTeacherEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFacultyEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFacultyFacultyKeyword_3_0 = (Keyword)cFacultyEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCourseOfStudyEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCourseOfStudyCourseOfStudyKeyword_4_0 = (Keyword)cCourseOfStudyEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cCourseEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cCourseCourseKeyword_5_0 = (Keyword)cCourseEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum SchoolElement:
		//	School | Student | Teacher | Faculty | CourseOfStudy | Course;
		public EnumRule getRule() { return rule; }

		//School | Student | Teacher | Faculty | CourseOfStudy | Course
		public Alternatives getAlternatives() { return cAlternatives; }

		//School
		public EnumLiteralDeclaration getSchoolEnumLiteralDeclaration_0() { return cSchoolEnumLiteralDeclaration_0; }

		//"School"
		public Keyword getSchoolSchoolKeyword_0_0() { return cSchoolSchoolKeyword_0_0; }

		//Student
		public EnumLiteralDeclaration getStudentEnumLiteralDeclaration_1() { return cStudentEnumLiteralDeclaration_1; }

		//"Student"
		public Keyword getStudentStudentKeyword_1_0() { return cStudentStudentKeyword_1_0; }

		//Teacher
		public EnumLiteralDeclaration getTeacherEnumLiteralDeclaration_2() { return cTeacherEnumLiteralDeclaration_2; }

		//"Teacher"
		public Keyword getTeacherTeacherKeyword_2_0() { return cTeacherTeacherKeyword_2_0; }

		//Faculty
		public EnumLiteralDeclaration getFacultyEnumLiteralDeclaration_3() { return cFacultyEnumLiteralDeclaration_3; }

		//"Faculty"
		public Keyword getFacultyFacultyKeyword_3_0() { return cFacultyFacultyKeyword_3_0; }

		//CourseOfStudy
		public EnumLiteralDeclaration getCourseOfStudyEnumLiteralDeclaration_4() { return cCourseOfStudyEnumLiteralDeclaration_4; }

		//"CourseOfStudy"
		public Keyword getCourseOfStudyCourseOfStudyKeyword_4_0() { return cCourseOfStudyCourseOfStudyKeyword_4_0; }

		//Course
		public EnumLiteralDeclaration getCourseEnumLiteralDeclaration_5() { return cCourseEnumLiteralDeclaration_5; }

		//"Course"
		public Keyword getCourseCourseKeyword_5_0() { return cCourseCourseKeyword_5_0; }
	}
	
	private final SchoolDatabaseElements pSchoolDatabase;
	private final SchoolElements pSchool;
	private final QueryElements pQuery;
	private final FacultyElements pFaculty;
	private final CourseOfStudyElements pCourseOfStudy;
	private final CourseElements pCourse;
	private final StudentElements pStudent;
	private final TeacherElements pTeacher;
	private final EStringElements pEString;
	private final CourseResultElements pCourseResult;
	private final EBigIntegerElements pEBigInteger;
	private final WhereElements pWhere;
	private final SchoolElementElements unknownRuleSchoolElement;
	private final BooleanExprElements pBooleanExpr;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SchooldslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSchoolDatabase = new SchoolDatabaseElements();
		this.pSchool = new SchoolElements();
		this.pQuery = new QueryElements();
		this.pFaculty = new FacultyElements();
		this.pCourseOfStudy = new CourseOfStudyElements();
		this.pCourse = new CourseElements();
		this.pStudent = new StudentElements();
		this.pTeacher = new TeacherElements();
		this.pEString = new EStringElements();
		this.pCourseResult = new CourseResultElements();
		this.pEBigInteger = new EBigIntegerElements();
		this.pWhere = new WhereElements();
		this.unknownRuleSchoolElement = new SchoolElementElements();
		this.pBooleanExpr = new BooleanExprElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.ps3.school.Schooldsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//SchoolDatabase:
	//	"SchoolDatabase" "{" "school" school=School ("queries" "{" query+=Query ("," query+=Query)* "}")? "}";
	public SchoolDatabaseElements getSchoolDatabaseAccess() {
		return pSchoolDatabase;
	}
	
	public ParserRule getSchoolDatabaseRule() {
		return getSchoolDatabaseAccess().getRule();
	}

	//School:
	//	{School} name=EString "{" ("faculties" "{" faculty+=Faculty ("," faculty+=Faculty)* "}")? ("coursesofstudy" "{"
	//	courseofstudy+=CourseOfStudy ("," courseofstudy+=CourseOfStudy)* "}")? ("courses" "{" course+=Course (","
	//	course+=Course)* "}")? ("students" "{" student+=Student ("," student+=Student)* "}")? ("teachers" "{"
	//	teacher+=Teacher ("," teacher+=Teacher)* "}")? "}";
	public SchoolElements getSchoolAccess() {
		return pSchool;
	}
	
	public ParserRule getSchoolRule() {
		return getSchoolAccess().getRule();
	}

	//Query:
	//	{Query} "Query" "{" type=SchoolElement? ("where" where=Where)? "}";
	public QueryElements getQueryAccess() {
		return pQuery;
	}
	
	public ParserRule getQueryRule() {
		return getQueryAccess().getRule();
	}

	//Faculty:
	//	{Faculty} "Faculty" name=EString "{" ("coursesofstudy" "(" courseofstudy+=[CourseOfStudy|EString] (","
	//	courseofstudy+=[CourseOfStudy|EString])* ")")? "}";
	public FacultyElements getFacultyAccess() {
		return pFaculty;
	}
	
	public ParserRule getFacultyRule() {
		return getFacultyAccess().getRule();
	}

	//CourseOfStudy:
	//	"CourseOfStudy" name=EString "{" ("courses" "(" course+=[Course|EString] ("," course+=[Course|EString])* ")")?
	//	"faculty" faculty=[Faculty|EString] ("students" "(" student+=[Student|EString] ("," student+=[Student|EString])*
	//	")")? "}";
	public CourseOfStudyElements getCourseOfStudyAccess() {
		return pCourseOfStudy;
	}
	
	public ParserRule getCourseOfStudyRule() {
		return getCourseOfStudyAccess().getRule();
	}

	//Course:
	//	"Course" name=EString "{" ("courseNumber" courseNumber=EString)? ("enrolledStudents" "("
	//	enrolledStudent+=[Student|EString] ("," enrolledStudent+=[Student|EString])* ")")? "taughtBy"
	//	taughtBy=[Teacher|EString] ("courseresults" "{" courseresult+=CourseResult ("," courseresult+=CourseResult)* "}")?
	//	"}";
	public CourseElements getCourseAccess() {
		return pCourse;
	}
	
	public ParserRule getCourseRule() {
		return getCourseAccess().getRule();
	}

	//Student:
	//	"Student" name=EString "{" ("studentNumber" studentNumber=EString)? ("enrolledIn" "(" enrolledIn+=[Course|EString]
	//	("," enrolledIn+=[Course|EString])* ")")? "courseofstudy" courseofstudy=[CourseOfStudy|EString] "}";
	public StudentElements getStudentAccess() {
		return pStudent;
	}
	
	public ParserRule getStudentRule() {
		return getStudentAccess().getRule();
	}

	//Teacher:
	//	{Teacher} "Teacher" name=EString "{" ("teaches" "(" teaches+=[Course|EString] ("," teaches+=[Course|EString])* ")")?
	//	"}";
	public TeacherElements getTeacherAccess() {
		return pTeacher;
	}
	
	public ParserRule getTeacherRule() {
		return getTeacherAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//CourseResult:
	//	"CourseResult" "{" ("grade" grade=EBigInteger)? "student" student=[Student|EString] "}";
	public CourseResultElements getCourseResultAccess() {
		return pCourseResult;
	}
	
	public ParserRule getCourseResultRule() {
		return getCourseResultAccess().getRule();
	}

	//EBigInteger returns ecore::EBigInteger:
	//	"-"? INT;
	public EBigIntegerElements getEBigIntegerAccess() {
		return pEBigInteger;
	}
	
	public ParserRule getEBigIntegerRule() {
		return getEBigIntegerAccess().getRule();
	}

	//Where:
	//	"{" booleanexpr=BooleanExpr "}";
	public WhereElements getWhereAccess() {
		return pWhere;
	}
	
	public ParserRule getWhereRule() {
		return getWhereAccess().getRule();
	}

	//enum SchoolElement:
	//	School | Student | Teacher | Faculty | CourseOfStudy | Course;
	public SchoolElementElements getSchoolElementAccess() {
		return unknownRuleSchoolElement;
	}
	
	public EnumRule getSchoolElementRule() {
		return getSchoolElementAccess().getRule();
	}

	//BooleanExpr:
	//	{BooleanExpr} lhs=EString operator=EString rhs=EString ("and" and=BooleanExpr)? ("or" or=BooleanExpr)?;
	public BooleanExprElements getBooleanExprAccess() {
		return pBooleanExpr;
	}
	
	public ParserRule getBooleanExprRule() {
		return getBooleanExprAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
