/*
 * generated by Xtext
 */
package org.xtext.ps3.school;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SchooldslRuntimeModule extends org.xtext.ps3.school.AbstractSchooldslRuntimeModule {

}
